[%Escala]
ColNameHeader=True
Format=TabDelimited
MaxScanRows=0
CharacterSet=ANSI
Index=Escala
Col1="Escala" Char Width 11
Col2="NomeEmbarcacao" Char Width 55
Col3="CodigoIMO" Char Width 10
Col4="TipoBloqueio1" Char Width 40
Col5="MotivoBloqueio1" Char Width 60
Col6="JustificativaBloqueio1" LongChar Width 250
Col7="CPFResponsavelBloqueio1" Char Width 11
Col8="NomeResponsavelBloqueio1" LongChar Width 115
Col9="DataBloqueio1" Date 
Col10="HoraBloqueio1" Char Width 8
Col11="DesbloqueadoPeloTransportador1" Char Width 1
Col12="CPFResponsavelDesbloqueio1" Char Width 11
Col13="NomeResponsavelDesbloqueio1" LongChar Width 115
Col14="DataDesbloqueio1" Date
Col15="HoraDesbloqueio1" Char Width 8
Col16="JustificativaDesbloqueio1" LongChar Width 250
Col17="TipoBloqueio2" Char Width 40
Col18="MotivoBloqueio2" Char Width 60
Col19="JustificativaBloqueio2" LongChar Width 250
Col20="CPFResponsavelBloqueio2" Char Width 11
Col21="NomeResponsavelBloqueio2" LongChar Width 115
Col22="DataBloqueio2" Date 
Col23="HoraBloqueio2" Char Width 8
Col24="DesbloqueadoPeloTransportador2" Char Width 1
Col25="CPFResponsavelDesbloqueio2" Char Width 11
Col26="NomeResponsavelDesbloqueio2" LongChar Width 115
Col27="DataDesbloqueio2" Date
Col28="HoraDesbloqueio2" Char Width 8
Col29="JustificativaDesbloqueio2" LongChar Width 250
Col30="TipoBloqueio3" Char Width 40
Col31="MotivoBloqueio3" Char Width 60
Col32="JustificativaBloqueio3" LongChar Width 250
Col33="CPFResponsavelBloqueio3" Char Width 11
Col34="NomeResponsavelBloqueio3" LongChar Width 115
Col35="DataBloqueio3" Date 
Col36="HoraBloqueio3" Char Width 8
Col37="DesbloqueadoPeloTransportador3" Char Width 1
Col38="CPFResponsavelDesbloqueio3" Char Width 11
Col39="NomeResponsavelDesbloqueio3" LongChar Width 115
Col40="DataDesbloqueio3" Date
Col41="HoraDesbloqueio3" Char Width 8
Col42="JustificativaDesbloqueio3" LongChar Width 250
Col43="QuantidadeBloqueiosAtivos" Integer
Col44="IndicadorHistoricoBloqueios" Char Width 1
Col45="NomeAgenciaNavegacao" Char Width 60
Col46="CNPJAgenciaNavegacao" Char Width 14
Col47="DataPrevistaAtracacao" Date
Col48="DataEfetivaAtracacao" Date
Col49="DataPrevistaDesatracacao" Date
Col50="DataUltimaDesatracacao" Date