[%Conhecimento]
ColNameHeader=True
Format=TabDelimited
MaxScanRows=0
CharacterSet=ANSI
Index=Conhecimento
Col1="Conhecimento" Char Width 15
Col2="QuantidadeBloqueiosAtivos" Integer
Col3="QuantidadeBloqueiosInativos" Integer
Col4="TipoBloqueio1" Char Width 40
Col5="MotivoBloqueio1" Char Width 60
Col6="JustificativaBloqueio1" LongChar Width 250
Col7="CPFResponsavelBloqueio1" Char Width 11
Col8="NomeResponsavelBloqueio1" LongChar Width 115
Col9="DataBloqueio1" Date 
Col10="HoraBloqueio1" Char Width 8
Col11="DesbloqueadoPeloTransportador1" Char Width 1
Col12="CPFResponsavelDesbloqueio1" Char Width 11
Col13="NomeResponsavelDesbloqueio1" LongChar Width 115
Col14="DataDesbloqueio1" Date
Col15="HoraDesbloqueio1" Char Width 8
Col16="JustificativaDesbloqueio1" LongChar Width 250
Col17="TipoBloqueio2" Char Width 40
Col18="MotivoBloqueio2" Char Width 60
Col19="JustificativaBloqueio2" LongChar Width 250
Col20="CPFResponsavelBloqueio2" Char Width 11
Col21="NomeResponsavelBloqueio2" LongChar Width 115
Col22="DataBloqueio2" Date 
Col23="HoraBloqueio2" Char Width 8
Col24="DesbloqueadoPeloTransportador2" Char Width 1
Col25="CPFResponsavelDesbloqueio2" Char Width 11
Col26="NomeResponsavelDesbloqueio2" LongChar Width 115
Col27="DataDesbloqueio2" Date
Col28="HoraDesbloqueio2" Char Width 8
Col29="JustificativaDesbloqueio2" LongChar Width 250
Col30="TipoBloqueio3" Char Width 40
Col31="MotivoBloqueio3" Char Width 60
Col32="JustificativaBloqueio3" LongChar Width 250
Col33="CPFResponsavelBloqueio3" Char Width 11
Col34="NomeResponsavelBloqueio3" LongChar Width 115
Col35="DataBloqueio3" Date 
Col36="HoraBloqueio3" Char Width 8
Col37="DesbloqueadoPeloTransportador3" Char Width 1
Col38="CPFResponsavelDesbloqueio3" Char Width 11
Col39="NomeResponsavelDesbloqueio3" LongChar Width 115
Col40="DataDesbloqueio3" Date
Col41="HoraDesbloqueio3" Char Width 8
Col42="JustificativaDesbloqueio3" LongChar Width 250
Col43="TipoBloqueio4" Char Width 40
Col44="MotivoBloqueio4" Char Width 60
Col45="JustificativaBloqueio4" LongChar Width 250
Col46="CPFResponsavelBloqueio4" Char Width 11
Col47="NomeResponsavelBloqueio4" LongChar Width 115
Col48="DataBloqueio4" Date 
Col49="HoraBloqueio4" Char Width 8
Col50="DesbloqueadoPeloTransportador4" Char Width 1
Col51="CPFResponsavelDesbloqueio4" Char Width 11
Col52="NomeResponsavelDesbloqueio4" LongChar Width 115
Col53="DataDesbloqueio4" Date
Col54="HoraDesbloqueio4" Char Width 8
Col55="JustificativaDesbloqueio4" LongChar Width 250
Col56="IndicadorHistoricoBloqueios" Char Width 1
Col57="IndicadorHistoricoPedidoRetificacao" Char Width 1
Col58="NumeroBL" Char Width 18
Col59="DataEmissao" Date
Col60="Tipo" Char Width 4
Col61="ConhecimentoMaster" Char Width 15
Col62="IndicadorBLServico" Char Width 1
Col63="NumeroBLServico" Char Width 15
Col64="IndicadorPossuiBLServico" Char Width 1
Col65="QuantidadeBLServico" Integer
Col66="IndicadorShipConveniense" Char Width 1
Col67="ConteinerShipConveniense1" Char Width 11
Col68="ConteinerShipConveniense2" Char Width 11
Col69="ConteinerShipConveniense3" Char Width 11
Col70="CodigoPortoOrigem" Char Width 5
Col71="NomePortoOrigem" Char Width 60
Col72="CodigoPortoDestino" Char Width 5
Col73="NomePortoDestino" Char Width 60
Col74="NomeConsignatario" LongChar Width 115
Col75="CPFCNPJConsignatario" Char Width 14
Col76="ConsignatarioEstrangeiro" Char Width 1
Col77="NomeConsignatarioEstrangeiro" Char Width 55
Col78="PassaporteEstrangeiro" Char Width 30
Col79="IndicadorBLaOrdem" Char Width 1
Col80="IndicadorCargaEntregaExterior" Char Width 1
Col81="CodigoPaisEntrega" Char Width 2
Col82="NomePaisEntrega" Char Width 60
Col83="IdentificacaoConsignatario" LongChar Width 253
Col84="NomeNotificado" LongChar Width 115
Col85="CPFCNPJNotificado" Char Width 14
Col86="IdentificacaoNotificado" LongChar Width 253
Col87="DescricaoMercadoria" LongChar Width 253
Col88="ContinuacaoDescricaoMercadoria" Char Width 1
Col89="Situacao" Char Width 35
Col90="DataSituacao" Date
Col91="CodigoSituacao" Char Width 2
Col92="CodigoDocumentoDespacho" Char Width 3
Col93="NumeroDocumentoDespacho" Char Width  10
Col94="CodigoDaSituacaoDespacho" Char Width 2
Col95="SituacaoDespacho" Char Width 80
Col96="DataSituacaoDespacho" Date
Col97="CanalDespachoDI" Char Width 60
Col98="TipoDocDespachoNaturezaDSI" LongChar Width 120
Col99="NomeRAArmazenamento" Char Width 60
Col100="CodigoRAArmazenamento" Char Width 7
Col101="NomeEmbarcador" LongChar Width 115
Col102="CPFCNPJEmbarcador" Char Width 14
Col103="IdentificacaoEmbarcador" LongChar Width 253
Col104="NomeAgenteNavegacao" LongChar Width 115
Col105="CodigoAgenteNavegacao" Char Width 14
Col106="NomeEmpresaNavegacaoDesconsolidadora" LongChar Width 115
Col107="CodigoEmpresaNavegacaoDesconsolidadora" Char Width 14
Col108="NomeAgenteNavegacaoDesconsolidador" LongChar Width 115
Col109="CodigoAgenteNavegacaoDesconsolidador" Char Width 14
Col110="NomeNavioPrimeiroTransporte" Char Width 60
Col111="DataEmissaoBLPrimeiroTransporte" Date
Col112="BLPrimeiroTransporte" Char Width 18
Col113="ValorFrete" Float
Col114="MoedaFrete" Char Width 55
Col115="ModalidadeFrete" Char Width 15
Col116="RecolhimentoFrete" Char Width 7
Col117="IndicadorCargaConteinerizada" Char Width 1