"""primeira versao

Revision ID: a22fe6602469
Revises: 
Create Date: 2017-11-11 13:56:06.277808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22fe6602469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametrosrisco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('valoresparametro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_campo', sa.String(length=50), nullable=True),
    sa.Column('tipo_filtro', sa.Enum('startswith', 'contains', 'extractall', name='filtro'), nullable=True),
    sa.Column('risco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['risco_id'], ['parametrosrisco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_campo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valoresparametro')
    op.drop_table('parametrosrisco')
    # ### end Alembic commands ###
