"""Bases

Revision ID: b16fc85d6f3f
Revises: a22fe6602469
Create Date: 2017-11-14 10:37:07.048963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16fc85d6f3f'
down_revision = 'a22fe6602469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('caminho', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caminho'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tabelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csv', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('primario', sa.Integer(), nullable=True),
    sa.Column('estrangeiro', sa.Integer(), nullable=True),
    sa.Column('pai_id', sa.Integer(), nullable=True),
    sa.Column('base_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['bases.id'], ),
    sa.ForeignKeyConstraint(['pai_id'], ['tabelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('csv'),
    sa.UniqueConstraint('descricao')
    )
    op.add_column('parametrosrisco', sa.Column('nome_campo', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'parametrosrisco', ['nome_campo'])
    op.drop_column('parametrosrisco', 'nome')
    op.add_column('valoresparametro', sa.Column('valor', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'valoresparametro', ['valor'])
    op.drop_column('valoresparametro', 'nome_campo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valoresparametro', sa.Column('nome_campo', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'valoresparametro', type_='unique')
    op.drop_column('valoresparametro', 'valor')
    op.add_column('parametrosrisco', sa.Column('nome', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'parametrosrisco', type_='unique')
    op.drop_column('parametrosrisco', 'nome_campo')
    op.drop_table('tabelas')
    op.drop_table('bases')
    # ### end Alembic commands ###
